-- MySQL Script generated by MySQL Workbench
-- Tue Apr 10 14:25:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema project1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `project1` ;

-- -----------------------------------------------------
-- Schema project1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project1` DEFAULT CHARACTER SET utf8 ;
USE `project1` ;

-- -----------------------------------------------------
-- Table `project1`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project1`.`categories` ;

CREATE TABLE IF NOT EXISTS `project1`.`categories` (
  `CategoryID` INT(11) NOT NULL AUTO_INCREMENT,
  `CategoryName` VARCHAR(45) NOT NULL,
  `Active` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`CategoryID`),
  UNIQUE INDEX `CategoryName_UNIQUE` (`CategoryName` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project1`.`manufacturers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project1`.`manufacturers` ;

CREATE TABLE IF NOT EXISTS `project1`.`manufacturers` (
  `ManufacturerID` INT(11) NOT NULL AUTO_INCREMENT,
  `ManufacturerName` VARCHAR(45) NOT NULL,
  `Active` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ManufacturerID`),
  UNIQUE INDEX `ManufacturerName_UNIQUE` (`ManufacturerName` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project1`.`stocks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project1`.`stocks` ;

CREATE TABLE IF NOT EXISTS `project1`.`stocks` (
  `StockID` INT(11) NOT NULL AUTO_INCREMENT,
  `StockName` VARCHAR(45) NOT NULL,
  `Active` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`StockID`),
  UNIQUE INDEX `StockName_UNIQUE` (`StockName` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project1`.`goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project1`.`goods` ;

CREATE TABLE IF NOT EXISTS `project1`.`goods` (
  `GoodsID` INT(11) NOT NULL AUTO_INCREMENT,
  `GoodsCode` VARCHAR(11) NOT NULL,
  `GoodsName` VARCHAR(100) NOT NULL,
  `ExpiryDate` DATE NULL DEFAULT NULL,
  `ImportedPrice` INT(11) NOT NULL DEFAULT '0',
  `ExportedPrice` INT(11) NOT NULL DEFAULT '0',
  `InStock` INT(11) NOT NULL DEFAULT '0',
  `CategoryID` INT(11) NOT NULL,
  `ManufacturerID` INT(11) NOT NULL,
  `StockID` INT(11) NOT NULL,
  PRIMARY KEY (`GoodsID`),
  UNIQUE INDEX `goodsCode_UNIQUE` (`GoodsCode` ASC),
  INDEX `fk_goods_categories_idx` (`CategoryID` ASC),
  INDEX `fk_goods_manufacturers_idx` (`ManufacturerID` ASC),
  INDEX `fk_goods_stocks_idx` (`StockID` ASC),
  CONSTRAINT `fk_goods_categories`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `project1`.`categories` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_goods_manufacturers`
    FOREIGN KEY (`ManufacturerID`)
    REFERENCES `project1`.`manufacturers` (`ManufacturerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_goods_stocks`
    FOREIGN KEY (`StockID`)
    REFERENCES `project1`.`stocks` (`StockID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `project1`.`stocks` (`StockName`) VALUES ('Văn phòng phẩm');
INSERT INTO `project1`.`stocks` (`StockName`) VALUES ('Thực phẩm');
INSERT INTO `project1`.`stocks` (`StockName`) VALUES ('Điện tử');
INSERT INTO `project1`.`stocks` (`StockName`) VALUES ('Vật liệu');
INSERT INTO `project1`.`stocks` (`StockName`) VALUES ('Vật tư');
INSERT INTO `project1`.`stocks` (`StockName`) VALUES ('Điện máy');
INSERT INTO `project1`.`stocks` (`StockName`) VALUES ('Nội thất');
INSERT INTO `project1`.`stocks` (`StockName`) VALUES ('Sách');
INSERT INTO `project1`.`stocks` (`StockName`) VALUES ('Trang sức');




INSERT INTO `project1`.`categories` (`CategoryName`) VALUES ('Máy tính');
INSERT INTO `project1`.`categories` (`CategoryName`) VALUES ('Điện thoại');
INSERT INTO `project1`.`categories` (`CategoryName`) VALUES ('Tivi');
INSERT INTO `project1`.`categories` (`CategoryName`) VALUES ('Bút');
INSERT INTO `project1`.`categories` (`CategoryName`) VALUES ('PC');
INSERT INTO `project1`.`categories` (`CategoryName`) VALUES ('Vở');
INSERT INTO `project1`.`categories` (`CategoryName`) VALUES ('Sách');
INSERT INTO `project1`.`categories` (`CategoryName`) VALUES ('Thực phẩm');




INSERT INTO `project1`.`manufacturers` (`ManufacturerName`) VALUES ('Apple');
INSERT INTO `project1`.`manufacturers` (`ManufacturerName`) VALUES ('Thiên Long');
INSERT INTO `project1`.`manufacturers` (`ManufacturerName`) VALUES ('Sony');
INSERT INTO `project1`.`manufacturers` (`ManufacturerName`) VALUES ('Calofic');
INSERT INTO `project1`.`manufacturers` (`ManufacturerName`) VALUES ('Panasonic');
INSERT INTO `project1`.`manufacturers` (`ManufacturerName`) VALUES ('Xuân Hòa');
INSERT INTO `project1`.`manufacturers` (`ManufacturerName`) VALUES ('Asus');
INSERT INTO `project1`.`manufacturers` (`ManufacturerName`) VALUES ('Samsung');
INSERT INTO `project1`.`manufacturers` (`ManufacturerName`) VALUES ('Dell');
INSERT INTO `project1`.`manufacturers` (`ManufacturerName`) VALUES ('Hồng Hà');
INSERT INTO `project1`.`manufacturers` (`ManufacturerName`) VALUES ('Vinamilk');
INSERT INTO `project1`.`manufacturers` (`ManufacturerName`) VALUES ('Acecook');




INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0001','Máy phay mộng đa năng 5 động cơ','2020-02-17','778315','376931','115','2','9','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0002','Than hoạt tính sọ dừa ','2022-06-27','723794','208223','9','1','4','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0003','Ghế tạ đa năng','2030-02-25','368367','435698','102','6','12','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0004','Nệm, gối cao su thiên nhiên','2022-07-19','439115','737831','171','3','3','3');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0005','Phân NPK','2022-01-03','241940','809755','199','6','1','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0006','Nước cốt dừa đóng lon','2024-06-24','978817','629299','178','7','9','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0007','Tinh bột sắn, BDSTAR','2022-10-05','593473','527179','133','6','2','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0008','Bánh tráng dẻo xuất khẩu','2023-01-31','355253','981331','77','5','1','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0009','Máy phát điện','2018-04-10','925429','884915','48','4','11','3');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0010','Kẹo dừa ca cao','2022-11-18','552528','419970','120','7','8','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0011','Muối chanh ớt DASAVI','2023-07-24','664506','225368','163','1','8','3');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0012','Ô Long kim tuyên trà','2020-12-29','104379','221639','168','6','3','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0013','Dây chuyền chế biến bột cá','2018-10-27','626429','181038','165','4','9','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0014','Bao bì nhựa cao cấp','2019-11-02','152770','704862','49','4','5','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0015','Máng phản quang T5 - hiệu Elink','2029-12-17','952692','655657','178','3','1','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0016','Bồn inox, Tank inox','2027-05-14','379594','760118','14','7','10','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0017','Cặp cán bộ C11864; cặp học sinh CA1216','2024-03-19','671822','745119','93','7','11','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0018','Chè Ô Long','2027-11-03','579393','801109','190','6','1','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0019','Nước mắm Tứ tuyệt - Nước mắm ruốc hiệu con cá vàng','2029-12-22','515081','812877','27','7','2','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0020','Máy bóc vỏ lụa nhân hạt điều','2019-05-08','639986','349937','80','1','3','3');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0021','Kính cường lực','2028-03-04','645379','291297','25','1','5','3');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0022','Máy tuốt lúa Tân Việt','2023-04-17','300104','747561','168','4','1','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0023','Miến dong Nhất Thiện Ba Bể','2027-05-21','401069','999219','168','3','3','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0024','Kẹo Cu đơ Phong Nga','2022-01-03','593673','890869','194','7','3','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0025','Nước mắm Vạn Phần','2029-08-31','543016','222786','38','6','3','3');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0026','Lạp xưởng Mai Quế Lộ hút chân không hiệu Quãng Trân','2030-04-01','203519','620236','190','2','10','3');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0027','Chè xanh Quyết Thắng','2026-07-12','141934','385207','169','7','2','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0028','Cá bò tẩm gia vị','2020-02-20','732405','243382','169','6','4','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0029','Nước mắm Nam Phan','2018-04-18','356846','746306','132','5','7','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0030','Đặc sản mỳ gạo Chũ truyền thống','2021-09-25','271505','563289','20','2','10','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0031','Trà Shan tuyết công phu Độ Khoa','2022-03-04','773563','887593','27','7','8','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0032','Cà phê Tâm Châu hộp trống','2027-06-24','275866','225099','19','7','11','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0033','Máy làm nhang tự động','2019-08-08','234041','798384','157','6','9','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0034','Máy gieo hạt tự động thế hệ mới','2023-12-17','822633','316704','6','6','3','3');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0035','Gạch không nung chống thấm','2021-05-05','249756','300008','112','6','8','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0036','Cặp phao cứu sinh','2023-09-05','809638','831932','171','4','3','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0037','Bộ sản phẩm Composite FRP','2026-02-07','964496','133544','186','3','1','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0038','Nhóm SP: Jăm  bông, Lạp xường','2019-09-15','912768','770467','41','1','10','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0039','Trà Ô Long ','2027-02-22','535995','359348','109','1','9','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0040','Chẹt vận chuyển máy nông nghiệp','2029-10-15','144019','687403','186','7','12','3');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0041','Kéo cắt tỉa đa năng, pl','2018-10-22','836164','786972','165','3','1','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0042','Bộ sản phẩm thủ công mỹ nghệ: Mũ cói, Rổ cói, Mũ giấy','2018-10-05','348723','591283','182','3','1','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0043','Rào chắn trẻ em ','2020-10-26','519057','618326','110','4','9','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0044','Cà phê phin giấy','2020-02-05','635812','147778','4','7','2','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0045','Dây chuyền sản xuất bánh hỏi tự động','2024-02-24','780881','105181','9','7','10','3');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0046','Máy kéo lúa','2019-02-27','329575','328300','146','2','6','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0047','Que hàn điện xuyên Á, Xuyen A-XA421 và A-H6013','2021-07-08','148404','378156','40','5','6','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0048','Bộ sản phẩm đồ thờ men rạn giả cổ đắp nổi ','2020-03-13','267349','697133','62','4','6','3');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0049','Vài thiều nước đường đóng hộp','2024-07-25','388448','960907','124','5','5','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0050','Miến Việt Cường','2029-05-10','373469','596160','92','4','2','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0051','Nha đam tươi','2024-05-05','195105','830625','66','5','10','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0052','Cà phê Hương chồn','2027-05-12','391636','181139','163','6','10','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0053','Dàn cày bảy chảo','2023-09-28','170009','287191','166','3','4','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0054','Bộ lọ gốm hoa văn cách điệu hoa cúc dây  ','2029-06-22','640051','867233','130','6','6','3');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0055','TULIPAN SET ','2024-02-24','291780','101933','122','6','9','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0056','Rèm gỗ nội thất','2028-11-10','761370','844874','160','4','9','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0057','Khung trang trí treo tường','2019-09-10','133907','678853','57','6','1','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0058','Bộ bàn ghế làm việc','2025-11-04','833453','670510','128','1','7','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0059','Bộ kết nối cầu sau ','2022-11-17','238610','813154','136','4','9','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0060','Tiêu Tiên Phước','2027-11-03','828901','233651','42','2','2','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0061','Hạt sen sấy ','2019-12-14','479512','885498','140','6','12','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0062','Nước mắm  Khải Hoàn','2028-09-26','707834','520989','171','4','4','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0063','Nước mắm Gia Hỷ 60N 500ml không phụ gia','2029-12-04','620320','193587','46','6','2','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0064','Cửa xếp Thống Nhất','2020-09-24','563166','889834','9','4','1','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0065','Khung xe đạp sắt và inox','2026-10-31','993170','182498','120','6','2','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0066','Máy ép củi trấu, BL-ET250','2028-06-30','167518','932680','100','6','4','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0067','Bàn ghế mây nhựa','2022-05-09','461716','512764','35','2','6','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0068','Bàn mây xếp','2028-07-26','377723','910944','66','2','12','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0069','Vải lụa tơ tằm Mã Châu','2029-07-20','561814','329789','100','6','4','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0070','Chè nõn Trại Cài Nguyên Việt','2023-11-24','978494','407840','5','1','11','3');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0071',' Rong nho khô','2028-10-29','928596','171733','196','6','5','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0072','Máy đầm dùi','2027-12-20','674885','774462','110','3','9','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0073','Túi làn hoa quai gỗ','2027-11-21','845658','873088','196','5','10','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0074','Hộp tròn đan mây ','2018-04-04','800742','183100','75','4','12','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0075','Bộ chăn ga gối','2030-01-26','804765','592284','105','1','11','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0076','Lan can đá','2030-05-21','470724','917517','154','5','12','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0077','Bộ sản phẩm chạm bạcđồ thờ Đồng Xâm','2021-12-14','300949','133689','112','4','11','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0078','Bộ bàn đôn ghế ngồi 2 chức năng','2029-12-30','151411','523641','91','1','7','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0079','Bộ ghế Sofa','2025-07-10','856229','645369','111','4','2','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0080','Bộ sản phẩm gốm men cổ','2023-07-13','652579','207416','43','5','2','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0081','Sọt đựng rác cây nấm bằng mây tre (AC540063)','2019-07-08','682828','170009','73','6','11','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0082','Chiếu cói gấp Xuân Hòa','2020-06-05','192641','692028','80','5','9','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0083','Ghế giả mây','2023-12-29','433248','598606','94','5','2','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0084','Bộ ăn 15 sản phẩm hoa Phù Dung','2018-11-12','639878','297650','50','2','2','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0085','Đèn đá','2022-11-07','757752','116859','177','7','11','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0086','Sản phẩm sứ dân dụng (đĩa bầu dục)','2021-07-23','228760','581058','199','2','7','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0087','Sứa Cửa Việt','2018-02-05','762945','646867','57','3','1','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0088','Cơm cháy chà bông','2024-07-20','924052','862207','56','2','4','5');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0089','Bánh hạnh nhân','2024-07-25','195689','125976','195','7','3','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0090','Củ quả sấy tổng hợp TCTH 200','2018-03-04','716398','922778','135','2','5','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0091','Nhóm sản phẩm: Sữa chua, sữa tươi thanh trùng','2029-08-17','209620','603933','99','7','3','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0092','Nước mắm Phan Thiết Mũi Né','2021-05-09','393500','360999','20','2','10','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0093','Tinh dầu hoa hồi','2029-12-16','817467','244628','115','5','4','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0094','Nước tương Magic','2020-10-07','473072','134588','137','3','9','3');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0095','Tôm khô ','2021-10-28','895213','627101','30','6','2','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0096','Máy nạo vét ao hồ','2018-09-06','500157','401151','146','3','5','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0097','Ống gang thoát nước cầu đường bộ','2018-06-16','226630','756398','71','3','4','4');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0098','Nắp hố ga thoát nước (HOUSING ECO 425)','2023-04-16','319067','332698','57','6','5','2');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0099','Pat Caraka (Patk-1400)','2026-09-14','655260','515804','26','4','12','1');
INSERT INTO `project1`.`goods` (`GoodsCode`, `GoodsName`,`ExpiryDate`, `ImportedPrice`, `ExportedPrice`, `InStock`, `CategoryID`, `ManufacturerID`, `StockID`) VALUES ('G0100','Cụm SP trang bị tàu đánh bắt xa bờ','2022-07-25','194329','248887','59','3','6','3');
